language: python
env:
 - DJANGO_VERSION=1.3
 - DJANGO_VERSION=1.4
 - DJANGO_VERSION=1.5
python:
 - "2.6"
 - "2.7"
install:
 - pip install -q --use-mirrors Django==$DJANGO_VERSION django-override-settings
script: ./run.sh test
