language: python
env:
 - DJANGO="Django>=1.4,<1.4.99"
 - DJANGO="Django>=1.5,<1.5.99"
 - DJANGO="git+https://github.com/django/django.git@1.6c1#egg=Django"
python:
 - "2.6"
 - "2.7"
 - "3.3"
install:
 - pip install -q ${DJANGO}
script: ./run.sh test
matrix:
  exclude:
    - python: 3.3
      env: DJANGO="Django>=1.4,<1.4.99"
